spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ecom_user
    password: ecom123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: Shubhi
      password: Pass